import type { Metadata } from "next";
import "./globals.css";
import { Titillium_Web } from "next/font/google";
import { Landmark } from "lucide-react";

const font = Titillium_Web({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <header className="bg-primary text-primary-content p-4">
          <div className="flex justify-center items-center gap-2">
            <Landmark />
            <h1 className="text-2xl font-bold text-primary-content">Simple Bank</h1>
          </div>
        </header>
        {children}
        <footer className="bg-neutral text-neutral-content py-8">
          <div className="container mx-auto px-4 text-center">
            <p>&copy; 2024 Simple Bank. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
